-- =====================================================
-- IMPULSO DIGITAL - Base SQL inicial
-- Compatible con Supabase / PostgreSQL
-- Ejecutar directamente en Supabase SQL Editor
-- =====================================================

CREATE TABLE IF NOT EXISTS public.usuarios_admin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario VARCHAR(80) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    rol VARCHAR(50) NOT NULL DEFAULT 'admin',
    estado VARCHAR(30) NOT NULL DEFAULT 'activo',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.consultas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_cliente VARCHAR(120) NOT NULL,
    telefono VARCHAR(40),
    email VARCHAR(160),
    servicio VARCHAR(160),
    mensaje TEXT NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'pendiente',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.servicios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(140) NOT NULL UNIQUE,
    descripcion TEXT,
    estado VARCHAR(30) NOT NULL DEFAULT 'activo',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL UNIQUE,
    descripcion TEXT,
    estado VARCHAR(30) NOT NULL DEFAULT 'activo',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO public.servicios (nombre, descripcion, estado)
VALUES
    ('Desarrollo de paginas web', 'Sitios web profesionales para negocios y emprendedores.', 'activo'),
    ('Sistemas de gestion', 'Herramientas a medida para administrar procesos internos.', 'activo'),
    ('Tiendas online', 'E-commerce con estructura preparada para venta digital.', 'activo')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO public.categorias (nombre, descripcion, estado)
VALUES
    ('Web', 'Servicios relacionados con sitios y presencia digital.', 'activo'),
    ('Sistemas', 'Soluciones de gestion y automatizacion.', 'activo'),
    ('Marketing digital', 'Campanas, contenido y crecimiento online.', 'activo')
ON CONFLICT (nombre) DO NOTHING;

ALTER TABLE public.usuarios_admin ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consultas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.servicios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categorias ENABLE ROW LEVEL SECURITY;
